name             'chefapi_examples'
maintainer       'go-chef/chef project maintainers'
license          'All Rights Reserved'
description      'Test the chef server api'
version          '0.1.0'
chef_version     '>= 13'
depends          'chef-server'
depends          'fileutils'
depends          'jn_hosts'
depends          'line'
